### ISSUE TITLE
Consider adding line_length_adjustment_factor parameter

### ISSUE THREAD

**Issue by invisibleroads** [SEL-Columbia/networker#104]
If line_length_adjustment_factor is 1.2 and the straight distance between A and B is 100 kilometers, the length of line between A and B is assumed to be 120 kilometers.

Currently, we are approximating this effect by dividing each budget by the line_length_adjustment_factor (which should be mathematically equivalent to multiplying each distance by the line_length_adjustment_factor).

However, there might be distance calculations in networker that do not use the budget. To be safe, it might be clearer to be able to specify the line_length_adjustment_factor directly as a parameter to networker and modify the distance function in networker to use line_length_adjustment_factor.

**Comment by chrisnatali** [comment]
Might be good to have.  

It seems there are 3 distance relations in networker:  
1.  Nearest:
  a.  for determining the nearest edge to a point (uses RTree)
  b.  for determining nearest point to another point (uses KDTree)
2. Intersects:  Checking whether edges intersect
3. Budget > Distance to nearest node

I believe the line_length_adjustment_factor would only need to be considered in the last relation.  Looks like changes would need to be made  
[here](https://github.com/SEL-Columbia/networker/blob/c2d08f704fdfcc3a2e3f9841122b877942578839/networker/algorithms/mod_boruvka.py#L118)
and
[here](https://github.com/SEL-Columbia/networker/blob/c2d08f704fdfcc3a2e3f9841122b877942578839/networker/algorithms/mod_kruskal.py#L90)

**Comment by invisibleroads** [comment]
Since line_length_adjustment_factor only needs to be considered in checking whether the budget is greater than the distance to the nearest node, it seems like dividing the budget by the line_length_adjustment_factor is an acceptable workaround.

Since the line_length_adjustment_factor is used for both low voltage and medium voltage calculations, it may be better to keep the factor strictly in the pre-network calculations for now.
