### ISSUE TITLE
networkplanner vs networker difference with existing grid

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/networker#34]
In images below, green represents networkplanner's proposed grid, orange is networker's proposed grid.  It appears that networker's proposed grid is actually shorter (so it'd be more optimal from an overall cost perspective), but we should understand why.  

![2015-04-09-142520_173x238_scrot](https://cloud.githubusercontent.com/assets/740068/7073793/eaef45c0-dec3-11e4-8845-aedb0241cdec.png)

![2015-04-09-142535_163x253_scrot](https://cloud.githubusercontent.com/assets/740068/7073801/f144bd9c-dec3-11e4-9c0a-e022b2af4424.png)

**Comment by carbz** [comment]
This seems connected to Issue 117 on NetworkPlanner.  We see this sub optimal problem happening in the original build_network() functionality several times ... 
https://github.com/SEL-Columbia/networkplanner/issues/117

**Comment by chrisnatali** [comment]
Good reference.  Intuitively, because modBoruvka can revisit a segment if it doesn't pass the 'budget' (aka mvMax) test the 1st time, it should lead to a more optimal network than modKruskal (which only tests a segment once and moves on).  Would be interesting to compare networker's results for the same scenario @Naigege ran in SEL-Columbia/networkplanner#117

**Comment by chrisnatali** [comment]
Since a shortest edge between components may be tested *after* longer edges are tested in mod_boruvka, that shortest edge has a better chance of passing the mvmax test than in mod_kruskal.  

A simple case explaining the better optimality in mod_boruvka is now a [test case](https://github.com/SEL-Columbia/networker/blob/master/test/test_boruvka_v_kruskal.py#L17).
