### ISSUE TITLE
Existing Networks Seems to cause 'IntegrityError'

### ISSUE THREAD

**Issue by carbz** [SEL-Columbia/networker#37]
I'm testing the <code>run_networkplanner.py</code> on an osx-64 platform and am encountering an error when I introduce an existing-networks shapefile (it works fine otherwise).  I believe the same file worked on http://networkplanner.modilabs.org/ so not sure what's going wrong now... 

<code>>(networker)~/github/networkercarbz@RodimusPrime$ python scripts/run_networkplanner.py <a href = "https://github.com/carbz/network-planner/blob/master/NGA-analysis/preprocessing/config_jsons/networkplannner_config_test.json">networkplannner_config_test.json</a>  -o modeling/tests/</code>
<code>run failed: (IntegrityError) UNIQUE constraint failed: nodes.id u'INSERT INTO nodes (id, x, y, longitude, latitude, metric, is_fake, input, output) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' (11651, 7.499538624445761, 11.420471652741268, 7.499538624445761, 11.420471652741268, None, 1, None, None)</code>

**Comment by carbz** [comment]
To test this, I changed the <code>existing_networks</code> file and am getting another related error.  Is there some oversight on specifying the existing_networks shapefile that may be causing this? 

<code>>(networker)~/github/networkercarbz@RodimusPrime$ python scripts/run_networkplanner.py networkplannner_config_test.json -o modeling/tests/</code>
<code>run failed: 'NoneType' object has no attribute 'GetLayerCount'</code>

**Comment by chrisnatali** [comment]
Separate problems.  The former is something I need to try to reproduce if you send me the inputs (nodes, config, existing-networks shapefile).  

The latter is more likely a matter of not finding the existing-shapefile as specified in the config.  I'd lump this latter issue into #38

**Comment by carbz** [comment]
fixed the latter. It was a syntactical error/tab completion issue while re-writing the .json

The former issue is caused by this <a href = "https://www.dropbox.com/sh/osttedsdffa7w7p/AACHppOKaJnOn7d9GyVNQYZ-a?dl=0">existing_networks<a> shapefile.

**Comment by chrisnatali** [comment]
FYI, this problem had to do with situations where more than one demand node connected to the same fake node.  In that situation, we were attempting to add the fake node to the dataset_store multiple times (causing the integrity error).  We're adding all fake nodes in a simpler way now which eliminates this possibility.

**Comment by carbz** [comment]
+1, issue resolved. local osx instance of networker now seems fully functional with existing-networks files specified. Thanks for the quick troubleshooting!
