### ISSUE TITLE
networks-proposed.shp overlaps separate subgraph(s) of networks-existing.shp

### ISSUE THREAD

**Issue by carbz** [SEL-Columbia/networker#40]
The output <code>networks-proposed.shp</code> seems to disregard cases where <code>networks-existing.shp</code> contains multiple subgraphs.  The proposed network preserves a single fake node from an existing subgraph.  However,its proposed lines seem oblivious/blind/ignorant of the other networks-existing subgraphs.  
![proposed-network_irregularities](https://cloud.githubusercontent.com/assets/1178209/7328959/c7ff209a-eaa7-11e4-8017-3c0e1cf75309.png)

**Comment by carbz** [comment]
This may be unrelated, but within the same large dataset testing, I'm observing a 'splotchy' <code>networks-proposed.shp</code>.  It is almost as if the optimization simulation finished prematurely and didn't continue building out the network.  Most of the 'mini-grid' communities had nonzero MVMax weights with significant demand. 
 
![image](https://cloud.githubusercontent.com/assets/1178209/7358182/d26b52b8-ed01-11e4-80ea-80b99a3b32c2.png)

**Comment by chrisnatali** [comment]
Several sub-issues

Projection onto existing grid:
- Failed to attach the existing grid nodes to the projection result (fixed)
- Existing grid is simplified by networkx.read_shp function.  Nodes between junctions (i.e. intermediate nodes of degree < 3) are dropped from edges.  The result is a projection onto an imaginary simplified edge:  


![2015-04-29-165538_686x619_scrot](https://cloud.githubusercontent.com/assets/740068/7401195/2dea0640-ee90-11e4-911e-05350631ceaf.png)

Need to modify networker's load_shp wrapper to address this.  Once this is fixed, we'll see if cycle problems still exist.

**Comment by chrisnatali** [comment]
Major problems addressed.  There's still the matter of existing sub-nets being allowed to connect to each other, which I've added as a separate issue (#43).  

![2015-05-01-152823_995x886_scrot](https://cloud.githubusercontent.com/assets/740068/7435885/e580905e-f015-11e4-905b-f67c90bbeae8.png)

**Comment by carbz** [comment]
Confirmed - same dataset no longer overlaps existing-grid multiple times.  A 'splotchy' network still results though... 

![image](https://cloud.githubusercontent.com/assets/1178209/7436627/5ff80e32-f01d-11e4-90da-dbe3b82fa617.png)
