### ISSUE TITLE
Adding existing grid results in disconnected nodes with sufficient budget

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/networker#44]
From @carbz and issue #40 

I'm observing a 'splotchy' networks-proposed.shp. It is almost as if the optimization simulation finished prematurely and didn't continue building out the network. Most of the 'mini-grid' communities had nonzero MVMax weights with significant demand.

![image](https://cloud.githubusercontent.com/assets/1178209/7358182/d26b52b8-ed01-11e4-80ea-80b99a3b32c2.png)

**Comment by chrisnatali** [comment]
This was a misunderstanding in the meaning of the minimum_node_count parameter.  It's related to #46, but is not an issue on it's own.

**Comment by carbz** [comment]
confirmed.  Setting a lower <code>minimum_node_count</code> value of 2 results in 100% interconnection.  

![splotches_resolved](https://cloud.githubusercontent.com/assets/1178209/7483715/2b7edbec-f34f-11e4-81ce-d4138d7cd853.png)
