### ISSUE TITLE
Add `single_existing_network` parameter

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/networker#46]
If True, then treat the existing grid as a single network throughout algorithm (i.e. for cycle detection, mvmax propagation and minimum_node_count check).  

If False, then treat existing grid sub-networks as distinct throughout.  

This is a compatibility issue since other tools expect network outputs where subnetworks have either 0 or 1 fake node.

**Comment by chrisnatali** [comment]
Consider using a network id to distinguish separate subnets

**Comment by carbz** [comment]
distinct sub-network presumption leads to some cycles of the <code>networks-proposed.shp</code>.  Although this feature may be useful if considering the viability of sub-networks/mini-grids remaining isolated vs interconnected, it is one of the main barrier to being able to easily sequence the outputs. 

![loop_ex1](https://cloud.githubusercontent.com/assets/1178209/7483640/7f293630-f34e-11e4-92c0-c4857014060b.png)
![loop_ex2](https://cloud.githubusercontent.com/assets/1178209/7483642/84f5ba2a-f34e-11e4-9a2c-ba310869468b.png)
