### ISSUE TITLE
Fix requirement versions #codereview #2015may21

### ISSUE THREAD

**Issue by vr2262** [SEL-Columbia/networker#55]
The requirements in [requirements.txt](https://github.com/SEL-Columbia/networker/blob/fc7593e3a8abfea16819fac80c40b9b28b35e176/requirements.txt) have no version specified, so doing `$ pip install -r requirements.txt` will get the latest version of each depedency. Generally this isn't a problem, but you can't rely on an external dependency to maintain its current public API forever.

You should specify the version of each dependency like
```python
numpy==1.9.2
```

I recommend using https://gemnasium.com to notify you of when your depedencies are no longer at the latest version so you can check for yourself that newer versions still work.

**Comment by chrisnatali** [comment]
Closed with #76
