### ISSUE TITLE
Networker Stopped in the process of merging network and nodes 

### ISSUE THREAD

**Issue by sherpashaky** [SEL-Columbia/networker#72]
This scenario was run with the selected part of the existing network that was problematic. 
!
![screenshot 2015-08-06 12 23 48](https://cloud.githubusercontent.com/assets/731717/9117122/37e283d6-3c36-11e5-9350-f5c6de0d1174.png)

**Comment by chrisnatali** [comment]
This appears to be due to the fact that the files feature type (Polygon) does not match the layer type (Polyline) AND that networkx is using the feature type to determine how to read the feature.

**Comment by chrisnatali** [comment]
Fixed in v0.2.5
