### ISSUE TITLE
UTM Projected Existing Network is not considered in the Network build

### ISSUE THREAD

**Issue by sherpashaky** [SEL-Columbia/networker#74]
When a scenario is run with an existing grid network projected in UTM system, the proposed network that "networkplanner" outputs via modelrunner does not consider the existing grid. The demographic file in this case is also in the same UTM projection system.

**Comment by chrisnatali** [comment]
This seems to not be an issue any longer.  We know that if demographics AND existing network are projected, then networker works correctly.  And we don't allow them to be in different spatial reference systems now.
